from pages.form_page import FormPage
from data.form_page_data import FormPageLocators as locators, FormPageData as data


class TestFormPage:
    def test_form_page_validate(self, browser):
        form_page = FormPage(browser)
        form_page.navigate()
        form_page.expect_field_is_required(locators.FIRST_NAME_INPUT)
        form_page.expect_field_is_required(locators.LAST_NAME_INPUT)
        form_page.expect_field_is_required(locators.EMAIL_INPUT)
        form_page.expect_field_is_required(locators.PHONE_NUMBER_INPUT)
        form_page.expect_field_is_required(locators.ADDRESS_INPUT_1)
        form_page.expect_field_is_required(locators.ADDRESS_INPUT_2)
        form_page.expect_field_is_required(locators.STATE_INPUT)
        form_page.expect_field_is_required(locators.POSTAL_CODE_INPUT)
        form_page.expect_field_is_required(locators.DATE_OF_BIRTH)
        form_page.expect_field_is_required(locators.I_AGREE_CHECKBOX)
        form_page.expect_input_type(locators.FIRST_NAME_INPUT, data.TYPE_TEXT)
        form_page.expect_input_type(locators.LAST_NAME_INPUT, data.TYPE_TEXT)
        form_page.expect_input_type(locators.EMAIL_INPUT, data.TYPE_EMAIL)
        form_page.expect_input_type(locators.PHONE_NUMBER_INPUT, data.TYPE_PHONE)
        form_page.expect_input_type(locators.ADDRESS_INPUT_2, data.TYPE_TEXT)
        form_page.expect_input_type(locators.ADDRESS_INPUT_1, data.TYPE_TEXT)
        form_page.expect_input_type(locators.STATE_INPUT, data.TYPE_TEXT)
        form_page.expect_input_type(locators.POSTAL_CODE_INPUT, data.TYPE_TEXT)
        form_page.expect_input_type(locators.FIRST_NAME_INPUT, data.TYPE_TEXT)
        form_page.expect_input_type(locators.DATE_OF_BIRTH, data.TYPE_DATE)
        form_page.expect_input_pattern(locators.EMAIL_INPUT, data.EMAIL_PATTERN)
        form_page.expect_input_pattern(locators.PHONE_NUMBER_INPUT, data.PHONE_PATTERN)

    def test_form_page_fill_fields(self, browser):
        form_page = FormPage(browser)
        form_page.navigate()
        form_page.fill_first_name()
        form_page.fill_last_name()
        form_page.fill_email()
        form_page.fill_phone_number()
        form_page.fill_address_1()
        form_page.fill_address_2()
        form_page.fill_state()
        form_page.fill_postal_code()
        form_page.fill_birthday()
        form_page.set_sex()
        form_page.set_country_code()
        form_page.expect_country_code()
        form_page.set_country()
        form_page.expect_country()
        form_page.check_checkbox_i_agree()
        form_page.click_btn_submit()
